#!/bin/bash
if [ $# -ne 1 ]; then
        # Print usage
        echo 'publishdraft DRAFT
        usage:
        ./publishdraft $FILENAME_SAFE_SUBJECT
        e.g.
        ./publishdraft my-subject-without-spaces
        '
            exit 1
fi
DRAFT=$1
DRAFT_NAME=$(echo $1|sed "s/_drafts\///")
NEWPOST=_posts/`date -I`-$DRAFT_NAME
mv $DRAFT $NEWPOST
echo "mv $DRAFT $NEWPOST"
echo "
you can now use your favorite editor to edit $NEWPOST
"
# vim $NEWPOST
