#!/usr/bin/env bash
set -eu
if [ $# -ne 1 ]; then
        # Print usage
        echo 'publishdraft DRAFT
        usage:
        ./publishdraft $FILENAME_SAFE_SUBJECT
        e.g.
        ./publishdraft my-subject-without-spaces
        '
            exit 1
fi
DRAFT_NAME=$1
DRAFT_FULLPATH=_drafts/${DRAFT_NAME}.md
NEWPOST=_posts/`date -I`-${DRAFT_NAME}.md
set -x
mv ${DRAFT_FULLPATH} ${NEWPOST}
set +x
${EDITOR} ${NEWPOST}
