export interface SiteTheme {
  id: string;
  name: string;
  category: 'original' | 'light' | 'oled' | 'dark-red' | 'dark-ambient' | 'solarized' | 'gruvbox' | 'catppuccin' | 'fun' | 'creative';
  isDark: boolean;
  colors: {
    bg: string;
    secondary: string;
    card: string;
    border: string;
    accent: string;
    hover: string;
    dim: string;
    text: string;
    textMuted: string;
  };
}

export const SITE_THEMES: SiteTheme[] = [
  // Original Themes
  {
    id: 'tekromancer',
    name: 'Tekromancer (Matrix)',
    category: 'original',
    isDark: true,
    colors: {
      bg: '#0a010d',
      secondary: '#14031a',
      card: 'rgba(22, 5, 32, 0.85)',
      border: '#3b104c',
      accent: '#33dd00',
      hover: '#44ff11',
      dim: '#11bb00',
      text: '#e5e7eb',
      textMuted: '#9ca3af',
    },
  },
  {
    id: 'midnite',
    name: 'Midnite (Cyan)',
    category: 'original',
    isDark: true,
    colors: {
      bg: '#09090b',
      secondary: '#121217',
      card: 'rgba(20, 20, 26, 0.9)',
      border: '#27272a',
      accent: '#38bdf8',
      hover: '#7dd3fc',
      dim: '#0284c7',
      text: '#f4f4f5',
      textMuted: '#a1a1aa',
    },
  },
  {
    id: 'alt',
    name: 'Alt (Gold/Navy)',
    category: 'original',
    isDark: true,
    colors: {
      bg: '#050b14',
      secondary: '#0a1526',
      card: 'rgba(14, 28, 48, 0.85)',
      border: '#1e3a5f',
      accent: '#eebf3f',
      hover: '#fcd34d',
      dim: '#d97706',
      text: '#f8fafc',
      textMuted: '#94a3b8',
    },
  },
  {
    id: 'print',
    name: 'Print (Clean Light)',
    category: 'original',
    isDark: false,
    colors: {
      bg: '#f9fafb',
      secondary: '#f3f4f6',
      card: '#ffffff',
      border: '#e5e7eb',
      accent: '#0f766e',
      hover: '#115e59',
      dim: '#134e4a',
      text: '#111827',
      textMuted: '#4b5563',
    },
  },

  // WinnegansFake Themes
  {
    id: 'daylight-pure',
    name: 'Daylight White',
    category: 'light',
    isDark: false,
    colors: {
      bg: '#ffffff',
      secondary: '#f9fafb',
      card: '#f9fafb',
      border: '#e5e7eb',
      accent: '#059669',
      hover: '#047857',
      dim: '#10b981',
      text: '#000000',
      textMuted: '#4b5563',
    },
  },
  {
    id: 'warm-parchment',
    name: 'Book Parchment',
    category: 'light',
    isDark: false,
    colors: {
      bg: '#fbf7ee',
      secondary: '#f4ede0',
      card: '#f4ede0',
      border: '#e2d5be',
      accent: '#b45309',
      hover: '#92400e',
      dim: '#d97706',
      text: '#2c2416',
      textMuted: '#786851',
    },
  },
  {
    id: 'obsidian-oled',
    name: 'Obsidian OLED',
    category: 'oled',
    isDark: true,
    colors: {
      bg: '#000000',
      secondary: '#080808',
      card: '#080808',
      border: '#262626',
      accent: '#10b981',
      hover: '#34d399',
      dim: '#059669',
      text: '#ffffff',
      textMuted: '#9ca3af',
    },
  },
  {
    id: 'obsidian-crimson',
    name: 'Obsidian Crimson',
    category: 'oled',
    isDark: true,
    colors: {
      bg: '#000000',
      secondary: '#0a0202',
      card: '#0a0202',
      border: '#2a0c0c',
      accent: '#9a2f2f',
      hover: '#ba3939',
      dim: '#ba3939',
      text: '#9a2f2f',
      textMuted: '#6f2222',
    },
  },
  {
    id: 'dark-crimson',
    name: 'Crimson Midnight',
    category: 'dark-red',
    isDark: true,
    colors: {
      bg: '#140507',
      secondary: '#220a0d',
      card: '#220a0d',
      border: '#4c1117',
      accent: '#e11d48',
      hover: '#f43f5e',
      dim: '#fb7185',
      text: '#fecdd3',
      textMuted: '#fda4af',
    },
  },
  {
    id: 'dark-ember',
    name: 'Blood Ember',
    category: 'dark-red',
    isDark: true,
    colors: {
      bg: '#180806',
      secondary: '#270e0a',
      card: '#270e0a',
      border: '#541c14',
      accent: '#ea580c',
      hover: '#f97316',
      dim: '#fb923c',
      text: '#fed7aa',
      textMuted: '#fb923c',
    },
  },
  {
    id: 'dark-burgundy',
    name: 'Burgundy Velvet',
    category: 'dark-red',
    isDark: true,
    colors: {
      bg: '#190a12',
      secondary: '#28101e',
      card: '#28101e',
      border: '#581c3f',
      accent: '#db2777',
      hover: '#ec4899',
      dim: '#f472b6',
      text: '#fce7f3',
      textMuted: '#f472b6',
    },
  },
  {
    id: 'slate-midnight',
    name: 'Slate Midnight',
    category: 'dark-ambient',
    isDark: true,
    colors: {
      bg: '#020617',
      secondary: '#0f172a',
      card: '#0f172a',
      border: '#1e293b',
      accent: '#10b981',
      hover: '#34d399',
      dim: '#059669',
      text: '#f1f5f9',
      textMuted: '#94a3b8',
    },
  },
  {
    id: 'solarized-amber',
    name: 'Dublin Amber',
    category: 'dark-ambient',
    isDark: true,
    colors: {
      bg: '#14120e',
      secondary: '#211d17',
      card: '#211d17',
      border: '#453a29',
      accent: '#f59e0b',
      hover: '#fbbf24',
      dim: '#d97706',
      text: '#fef3c7',
      textMuted: '#fcd34d',
    },
  },
  {
    id: 'neon-cyberpunk',
    name: 'Cyberpunk Neon',
    category: 'fun',
    isDark: true,
    colors: {
      bg: '#0b0813',
      secondary: '#161026',
      card: '#161026',
      border: '#3b2d5a',
      accent: '#06b6d4',
      hover: '#22d3ee',
      dim: '#a855f7',
      text: '#f5f3ff',
      textMuted: '#c4b5fd',
    },
  },
  {
    id: 'forest-glade',
    name: 'Emerald Forest',
    category: 'creative',
    isDark: true,
    colors: {
      bg: '#04130c',
      secondary: '#0a2318',
      card: '#0a2318',
      border: '#134e35',
      accent: '#10b981',
      hover: '#34d399',
      dim: '#059669',
      text: '#ecfdf5',
      textMuted: '#6ee7b7',
    },
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    category: 'solarized',
    isDark: true,
    colors: {
      bg: '#002b36',
      secondary: '#073642',
      card: '#073642',
      border: '#073642',
      accent: '#2aa198',
      hover: '#268bd2',
      dim: '#b58900',
      text: '#839496',
      textMuted: '#586e75',
    },
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    category: 'solarized',
    isDark: false,
    colors: {
      bg: '#fdf6e3',
      secondary: '#eee8d5',
      card: '#eee8d5',
      border: '#eee8d5',
      accent: '#268bd2',
      hover: '#2aa198',
      dim: '#b58900',
      text: '#657b83',
      textMuted: '#93a1a1',
    },
  },
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    category: 'gruvbox',
    isDark: true,
    colors: {
      bg: '#282828',
      secondary: '#3c3836',
      card: '#3c3836',
      border: '#504945',
      accent: '#fabd2f',
      hover: '#fe8019',
      dim: '#d79921',
      text: '#ebdbb2',
      textMuted: '#a89984',
    },
  },
  {
    id: 'gruvbox-light',
    name: 'Gruvbox Light',
    category: 'gruvbox',
    isDark: false,
    colors: {
      bg: '#fbf1c7',
      secondary: '#ebdbb2',
      card: '#ebdbb2',
      border: '#d5c4a1',
      accent: '#b57614',
      hover: '#af3a03',
      dim: '#b57614',
      text: '#3c3836',
      textMuted: '#7c6f64',
    },
  },
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    category: 'catppuccin',
    isDark: false,
    colors: {
      bg: '#eff1f5',
      secondary: '#e6e9ef',
      card: '#e6e9ef',
      border: '#ccd0da',
      accent: '#7287fd',
      hover: '#1e66f5',
      dim: '#8839ef',
      text: '#4c4f69',
      textMuted: '#6c6f85',
    },
  },
  {
    id: 'catppuccin-frappe',
    name: 'Catppuccin Frappé',
    category: 'catppuccin',
    isDark: true,
    colors: {
      bg: '#303446',
      secondary: '#292c3c',
      card: '#292c3c',
      border: '#414559',
      accent: '#ca9ee6',
      hover: '#8caaee',
      dim: '#babbf1',
      text: '#c6d0f5',
      textMuted: '#a5adce',
    },
  },
  {
    id: 'catppuccin-macchiato',
    name: 'Catppuccin Macchiato',
    category: 'catppuccin',
    isDark: true,
    colors: {
      bg: '#24273a',
      secondary: '#1e2030',
      card: '#1e2030',
      border: '#363a4f',
      accent: '#c6a0f6',
      hover: '#8aadf4',
      dim: '#b7bdf8',
      text: '#cad3f5',
      textMuted: '#a5adcb',
    },
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    category: 'catppuccin',
    isDark: true,
    colors: {
      bg: '#1e1e2e',
      secondary: '#181825',
      card: '#181825',
      border: '#313244',
      accent: '#cba6f7',
      hover: '#89b4fa',
      dim: '#b4befe',
      text: '#cdd6f4',
      textMuted: '#a6adc8',
    },
  },
];

export type ThemeId = (typeof SITE_THEMES)[number]['id'] | 'techromancer';
